package subfeature

// #include <sensors/sensors.h>
// #include <sensors/error.h>
// #cgo LDFLAGS: -lsensors
import "C"

import (
	"math"
)

//go:generate stringer -type=SubFeature
type SubFeature uint32

func (s SubFeature) Error() string {
	return s.String()
}

const (
	IN_INPUT       SubFeature = C.SENSORS_SUBFEATURE_IN_INPUT
	IN_MIN         SubFeature = C.SENSORS_SUBFEATURE_IN_MIN
	IN_MAX         SubFeature = C.SENSORS_SUBFEATURE_IN_MAX
	IN_LCRIT       SubFeature = C.SENSORS_SUBFEATURE_IN_LCRIT
	IN_CRIT        SubFeature = C.SENSORS_SUBFEATURE_IN_CRIT
	IN_AVERAGE     SubFeature = C.SENSORS_SUBFEATURE_IN_AVERAGE
	IN_LOWEST      SubFeature = C.SENSORS_SUBFEATURE_IN_LOWEST
	IN_HIGHEST     SubFeature = C.SENSORS_SUBFEATURE_IN_HIGHEST
	IN_ALARM       SubFeature = C.SENSORS_SUBFEATURE_IN_ALARM
	IN_MIN_ALARM   SubFeature = C.SENSORS_SUBFEATURE_IN_MIN_ALARM
	IN_MAX_ALARM   SubFeature = C.SENSORS_SUBFEATURE_IN_MAX_ALARM
	IN_BEEP        SubFeature = C.SENSORS_SUBFEATURE_IN_BEEP
	IN_LCRIT_ALARM SubFeature = C.SENSORS_SUBFEATURE_IN_LCRIT_ALARM
	IN_CRIT_ALARM  SubFeature = C.SENSORS_SUBFEATURE_IN_CRIT_ALARM

	FAN_INPUT     SubFeature = C.SENSORS_SUBFEATURE_FAN_INPUT
	FAN_MIN       SubFeature = C.SENSORS_SUBFEATURE_FAN_MIN
	FAN_MAX       SubFeature = C.SENSORS_SUBFEATURE_FAN_MAX
	FAN_ALARM     SubFeature = C.SENSORS_SUBFEATURE_FAN_ALARM
	FAN_FAULT     SubFeature = C.SENSORS_SUBFEATURE_FAN_FAULT
	FAN_DIV       SubFeature = C.SENSORS_SUBFEATURE_FAN_DIV
	FAN_BEEP      SubFeature = C.SENSORS_SUBFEATURE_FAN_BEEP
	FAN_PULSES    SubFeature = C.SENSORS_SUBFEATURE_FAN_PULSES
	FAN_MIN_ALARM SubFeature = C.SENSORS_SUBFEATURE_FAN_MIN_ALARM
	FAN_MAX_ALARM SubFeature = C.SENSORS_SUBFEATURE_FAN_MAX_ALARM

	TEMP_INPUT           SubFeature = C.SENSORS_SUBFEATURE_TEMP_INPUT
	TEMP_MAX             SubFeature = C.SENSORS_SUBFEATURE_TEMP_MAX
	TEMP_MAX_HYST        SubFeature = C.SENSORS_SUBFEATURE_TEMP_MAX_HYST
	TEMP_MIN             SubFeature = C.SENSORS_SUBFEATURE_TEMP_MIN
	TEMP_CRIT            SubFeature = C.SENSORS_SUBFEATURE_TEMP_CRIT
	TEMP_CRIT_HYST       SubFeature = C.SENSORS_SUBFEATURE_TEMP_CRIT_HYST
	TEMP_LCRIT           SubFeature = C.SENSORS_SUBFEATURE_TEMP_LCRIT
	TEMP_EMERGENCY       SubFeature = C.SENSORS_SUBFEATURE_TEMP_EMERGENCY
	TEMP_EMERGENCY_HYST  SubFeature = C.SENSORS_SUBFEATURE_TEMP_EMERGENCY_HYST
	TEMP_LOWEST          SubFeature = C.SENSORS_SUBFEATURE_TEMP_LOWEST
	TEMP_HIGHEST         SubFeature = C.SENSORS_SUBFEATURE_TEMP_HIGHEST
	TEMP_MIN_HYST        SubFeature = C.SENSORS_SUBFEATURE_TEMP_MIN_HYST
	TEMP_LCRIT_HYST      SubFeature = C.SENSORS_SUBFEATURE_TEMP_LCRIT_HYST
	TEMP_ALARM           SubFeature = C.SENSORS_SUBFEATURE_TEMP_ALARM
	TEMP_MAX_ALARM       SubFeature = C.SENSORS_SUBFEATURE_TEMP_MAX_ALARM
	TEMP_MIN_ALARM       SubFeature = C.SENSORS_SUBFEATURE_TEMP_MIN_ALARM
	TEMP_CRIT_ALARM      SubFeature = C.SENSORS_SUBFEATURE_TEMP_CRIT_ALARM
	TEMP_FAULT           SubFeature = C.SENSORS_SUBFEATURE_TEMP_FAULT
	TEMP_TYPE            SubFeature = C.SENSORS_SUBFEATURE_TEMP_TYPE
	TEMP_OFFSET          SubFeature = C.SENSORS_SUBFEATURE_TEMP_OFFSET
	TEMP_BEEP            SubFeature = C.SENSORS_SUBFEATURE_TEMP_BEEP
	TEMP_EMERGENCY_ALARM SubFeature = C.SENSORS_SUBFEATURE_TEMP_EMERGENCY_ALARM
	TEMP_LCRIT_ALARM     SubFeature = C.SENSORS_SUBFEATURE_TEMP_LCRIT_ALARM

	POWER_AVERAGE          SubFeature = C.SENSORS_SUBFEATURE_POWER_AVERAGE
	POWER_AVERAGE_HIGHEST  SubFeature = C.SENSORS_SUBFEATURE_POWER_AVERAGE_HIGHEST
	POWER_AVERAGE_LOWEST   SubFeature = C.SENSORS_SUBFEATURE_POWER_AVERAGE_LOWEST
	POWER_INPUT            SubFeature = C.SENSORS_SUBFEATURE_POWER_INPUT
	POWER_INPUT_HIGHEST    SubFeature = C.SENSORS_SUBFEATURE_POWER_INPUT_HIGHEST
	POWER_INPUT_LOWEST     SubFeature = C.SENSORS_SUBFEATURE_POWER_INPUT_LOWEST
	POWER_CAP              SubFeature = C.SENSORS_SUBFEATURE_POWER_CAP
	POWER_CAP_HYST         SubFeature = C.SENSORS_SUBFEATURE_POWER_CAP_HYST
	POWER_MAX              SubFeature = C.SENSORS_SUBFEATURE_POWER_MAX
	POWER_CRIT             SubFeature = C.SENSORS_SUBFEATURE_POWER_CRIT
	POWER_MIN              SubFeature = C.SENSORS_SUBFEATURE_POWER_MIN
	POWER_LCRIT            SubFeature = C.SENSORS_SUBFEATURE_POWER_LCRIT
	POWER_AVERAGE_INTERVAL SubFeature = C.SENSORS_SUBFEATURE_POWER_AVERAGE_INTERVAL
	POWER_ALARM            SubFeature = C.SENSORS_SUBFEATURE_POWER_ALARM
	POWER_CAP_ALARM        SubFeature = C.SENSORS_SUBFEATURE_POWER_CAP_ALARM
	POWER_MAX_ALARM        SubFeature = C.SENSORS_SUBFEATURE_POWER_MAX_ALARM
	POWER_CRIT_ALARM       SubFeature = C.SENSORS_SUBFEATURE_POWER_CRIT_ALARM
	POWER_MIN_ALARM        SubFeature = C.SENSORS_SUBFEATURE_POWER_MIN_ALARM
	POWER_LCRIT_ALARM      SubFeature = C.SENSORS_SUBFEATURE_POWER_LCRIT_ALARM

	ENERGY_INPUT SubFeature = C.SENSORS_SUBFEATURE_ENERGY_INPUT

	CURR_INPUT       SubFeature = C.SENSORS_SUBFEATURE_CURR_INPUT
	CURR_MIN         SubFeature = C.SENSORS_SUBFEATURE_CURR_MIN
	CURR_MAX         SubFeature = C.SENSORS_SUBFEATURE_CURR_MAX
	CURR_LCRIT       SubFeature = C.SENSORS_SUBFEATURE_CURR_LCRIT
	CURR_CRIT        SubFeature = C.SENSORS_SUBFEATURE_CURR_CRIT
	CURR_AVERAGE     SubFeature = C.SENSORS_SUBFEATURE_CURR_AVERAGE
	CURR_LOWEST      SubFeature = C.SENSORS_SUBFEATURE_CURR_LOWEST
	CURR_HIGHEST     SubFeature = C.SENSORS_SUBFEATURE_CURR_HIGHEST
	CURR_ALARM       SubFeature = C.SENSORS_SUBFEATURE_CURR_ALARM
	CURR_MIN_ALARM   SubFeature = C.SENSORS_SUBFEATURE_CURR_MIN_ALARM
	CURR_MAX_ALARM   SubFeature = C.SENSORS_SUBFEATURE_CURR_MAX_ALARM
	CURR_BEEP        SubFeature = C.SENSORS_SUBFEATURE_CURR_BEEP
	CURR_LCRIT_ALARM SubFeature = C.SENSORS_SUBFEATURE_CURR_LCRIT_ALARM
	CURR_CRIT_ALARM  SubFeature = C.SENSORS_SUBFEATURE_CURR_CRIT_ALARM

	HUMIDITY_INPUT SubFeature = C.SENSORS_SUBFEATURE_HUMIDITY_INPUT

	VID SubFeature = C.SENSORS_SUBFEATURE_VID

	INTRUSION_ALARM SubFeature = C.SENSORS_SUBFEATURE_INTRUSION_ALARM
	INTRUSION_BEEP  SubFeature = C.SENSORS_SUBFEATURE_INTRUSION_BEEP

	BEEP_ENABLE SubFeature = C.SENSORS_SUBFEATURE_BEEP_ENABLE

	UNKNOWN = math.MaxUint32
)
