// Code generated by "stringer -type=Type"; DO NOT EDIT.

package bus

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ANY - -1]
	_ = x[I2C-0]
	_ = x[PCI-1]
	_ = x[SPI-2]
	_ = x[VIRTUAL-3]
	_ = x[ACPI-4]
	_ = x[HID-5]
	_ = x[MDIO-6]
	_ = x[SCSI-7]
}

const _Type_name = "ANYI2CPCISPIVIRTUALACPIHIDMDIOSCSI"

var _Type_index = [...]uint8{0, 3, 6, 9, 12, 19, 23, 26, 30, 34}

func (i Type) String() string {
	i -= -1
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
